#!/usr/bin/env bash

set -ue

COMMIT_MSG_FILE=$1
CURRENT_COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
COMMIT_SOURCE=${2:-commit}
CURRENT_STORY_FILE="$HOME/.config/sso4k8s/current_story.txt"

if [[ ! -f "$CURRENT_STORY_FILE" ]]; then
  # no current story file...
  exit 0
fi

STORY_ID=$(head -n 1 "$CURRENT_STORY_FILE")
STORY_NAME=$(tail -n 1 "$CURRENT_STORY_FILE")

if grep "$STORY_ID" "$COMMIT_MSG_FILE"; then
  # file already contains the story id...
  exit 0
fi

LINES_TO_ADD="[#$STORY_ID]"
if [[ "$COMMIT_SOURCE" != message ]]; then
  LINES_TO_ADD="${LINES_TO_ADD}\n# $STORY_NAME"
fi

if grep "Signed-off-by" "$COMMIT_MSG_FILE"; then
  # if there is a signed-off-by, prepend the text to signed-off-by
  gsed -i -z "s/Signed-off-by: \(.*\)/${LINES_TO_ADD}\n\nSigned-off-by: \1/" "$COMMIT_MSG_FILE"
elif [[ "$COMMIT_SOURCE" == message ]]; then
  # if the -m flag was passed, append the text
  echo -e "$CURRENT_COMMIT_MSG\n\n$LINES_TO_ADD" > "$COMMIT_MSG_FILE"
elif [[ "$COMMIT_SOURCE" == commit ]]; then
  # if it's a regular commit, prepend to the commit message
  echo -e "\n\n${LINES_TO_ADD}\n\n$CURRENT_COMMIT_MSG" > "$COMMIT_MSG_FILE"
fi
