# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = "$all${custom.git-duet}$fill$time$line_break$character"

[time]
disabled = false

[fill]
symbol = " "

[custom.git-duet]
when = "git-change"
command = "git-initials"
