# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false


format = """
$directory\
$java\
$nodejs\
$kubernetes\
$git_branch\
$git_commit\
$git_status\
$git_state\
${custom.git-duet}\
$cmd_duration\
$fill\
$time\
$line_break\
$character"""

[cmd_duration]
format = '[$duration]($style)'
min_time=10_000

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "…/"

[time]
disabled = false
format = '[$time]($style)'

[fill]
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol$context]($style) '
style = 'blue'
[kubernetes.context_aliases]
# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
'gke_.*_(?P<var_cluster>[\w-]+)' = '$var_cluster'


[java]
format = '[${symbol}(${version})]($style) '
detect_files = ['pom.xml', 'build.gradle.kts', 'build.sbt', '.java-version', 'deps.edn', 'project.clj', 'build.boot', 'build.gradle', 'settings.gradle', 'settings.gradle.kts']
symbol = '☕️'
version_format = '${major}'

[nodejs]
format = '[$symbol$version]($style) '
style = 'green'
version_format = '${major}'

[git_status]
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'purple'

[custom.git-duet]
when = "git-change"
command = "git-initials"
style = 'white'
