name: default
root: ~/workspace/sso/sso4k8s

windows:
  - sso4k8s: {}
  - k9s:
      layout: even-horizontal
      panes:
        - kubectx kind-kind && k9s
        - ponysay 'Hello there!'
  - misc: {}
