name: default
root: ~/workspace/sso/sso4k8s

windows:
  - sso4k8s:
      panes:
      - ssh-load && git pull --ff-only && git fetch --prune
  - k9s:
      layout: even-horizontal
      panes:
        - kubectx kind-kind
  - misc: {}
