export PATH="$HOME/bin:$PATH"
export PATH="$HOME/workspace/go/bin:$PATH"
export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/Cellar/bash/5.2.15/bin:$PATH"
export PATH="/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:$PATH"
export PATH="/Library/Ruby/Gems/2.6.0/gems/cf-uaac-4.14.0/bin:$PATH"
